#############################################################################
# Makefile for building: Pong
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  Pong.pro
# Template: app
# Command: /Users/gabeorlanski/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile Pong.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = 
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I../../../../Qt/5.4/clang_64/mkspecs/macx-clang
QMAKE         = /Users/gabeorlanski/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Pong1.0.0
DISTDIR = /Users/gabeorlanski/Desktop/Plse\ save\ battery/QT\ project/Pong/.tmp/Pong1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -L/usr/local/lib -lsfml-graphics-d -lsfml-system-d -lsfml-network-d -lsfml-window-d -lthor-d 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Source/Application.cpp \
		Source/Command.cpp \
		Source/CommandQueue.cpp \
		Source/Entity.cpp \
		Source/Main.cpp \
		Source/ParallelTask.cpp \
		Source/Player.cpp \
		Source/SceneNode.cpp \
		Source/SpriteNode.cpp \
		Source/State.cpp \
		Source/StateStack.cpp \
		Source/Utility.cpp \
		Source/World.cpp \
		States/Source/GameState.cpp \
		Ball.cpp \
		Paddle.cpp \
		States/Source/MenuState.cpp \
		States/Source/PauseState.cpp \
		States/Source/NewLevel.cpp \
		Level.cpp 
OBJECTS       = Application.o \
		Command.o \
		CommandQueue.o \
		Entity.o \
		Main.o \
		ParallelTask.o \
		Player.o \
		SceneNode.o \
		SpriteNode.o \
		State.o \
		StateStack.o \
		Utility.o \
		World.o \
		GameState.o \
		Ball.o \
		Paddle.o \
		MenuState.o \
		PauseState.o \
		NewLevel.o \
		Level.o
DIST          = ../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		Pong.pro Include/Book/Application.hpp \
		Include/Book/Category.hpp \
		Include/Book/Command.hpp \
		Include/Book/CommandQueue.hpp \
		Include/Book/Entity.hpp \
		Include/Book/Foreach.hpp \
		Include/Book/ParallelTask.hpp \
		Include/Book/Player.hpp \
		Include/Book/ResourceHolder.hpp \
		Include/Book/ResourceIdentifiers.hpp \
		Include/Book/SceneNode.hpp \
		Include/Book/SpriteNode.hpp \
		Include/Book/State.hpp \
		Include/Book/StateIdentifiers.hpp \
		Include/Book/StateStack.hpp \
		Include/Book/Utility.hpp \
		Include/Book/World.hpp \
		States/Include/GameState.hpp \
		Ball.hpp \
		Paddle.hpp \
		States/Include/MenuState.hpp \
		States/Include/PauseState.hpp \
		Level.hpp \
		States/Include/NewLevel.hpp Source/Application.cpp \
		Source/Command.cpp \
		Source/CommandQueue.cpp \
		Source/Entity.cpp \
		Source/Main.cpp \
		Source/ParallelTask.cpp \
		Source/Player.cpp \
		Source/SceneNode.cpp \
		Source/SpriteNode.cpp \
		Source/State.cpp \
		Source/StateStack.cpp \
		Source/Utility.cpp \
		Source/World.cpp \
		States/Source/GameState.cpp \
		Ball.cpp \
		Paddle.cpp \
		States/Source/MenuState.cpp \
		States/Source/PauseState.cpp \
		States/Source/NewLevel.cpp \
		Level.cpp
QMAKE_TARGET  = Pong
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Pong

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pong.pro ../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		Pong.pro
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile Pong.pro
../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
Pong.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile Pong.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Application.o: Source/Application.cpp include/Book/Application.hpp \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		include/Book/ResourceIdentifiers.hpp \
		include/Book/Player.hpp \
		include/Book/Command.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		include/Book/StateStack.hpp \
		include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		include/Book/Utility.hpp \
		include/Book/Utility.inl \
		States/Include/GameState.hpp \
		include/Book/World.hpp \
		include/Book/SceneNode.hpp \
		include/Book/SpriteNode.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		include/Book/CommandQueue.hpp \
		Ball.hpp \
		include/Book/Entity.hpp \
		/usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/Touch.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		Paddle.hpp \
		Level.hpp \
		States/Include/MenuState.hpp \
		States/Include/PauseState.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Application.o Source/Application.cpp

Command.o: Source/Command.cpp include/Book/Command.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Command.o Source/Command.cpp

CommandQueue.o: Source/CommandQueue.cpp include/Book/CommandQueue.hpp \
		include/Book/Command.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		include/Book/SceneNode.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommandQueue.o Source/CommandQueue.cpp

Entity.o: Source/Entity.cpp include/Book/Entity.hpp \
		include/Book/SceneNode.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Entity.o Source/Entity.cpp

Main.o: Source/Main.cpp include/Book/Application.hpp \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		include/Book/ResourceIdentifiers.hpp \
		include/Book/Player.hpp \
		include/Book/Command.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		include/Book/StateStack.hpp \
		include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Source/Main.cpp

ParallelTask.o: Source/ParallelTask.cpp include/Book/ParallelTask.hpp \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Time.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParallelTask.o Source/ParallelTask.cpp

Player.o: Source/Player.cpp include/Book/Player.hpp \
		include/Book/Command.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		include/Book/CommandQueue.hpp \
		Paddle.hpp \
		include/Book/Entity.hpp \
		include/Book/SceneNode.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/Touch.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		include/Book/Foreach.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Source/Player.cpp

SceneNode.o: Source/SceneNode.cpp include/Book/SceneNode.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		include/Book/Command.hpp \
		include/Book/Foreach.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneNode.o Source/SceneNode.cpp

SpriteNode.o: Source/SpriteNode.cpp include/Book/SpriteNode.hpp \
		include/Book/SceneNode.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpriteNode.o Source/SpriteNode.cpp

State.o: Source/State.cpp include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		include/Book/StateStack.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o State.o Source/State.cpp

StateStack.o: Source/StateStack.cpp include/Book/StateStack.hpp \
		include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		include/Book/Foreach.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StateStack.o Source/StateStack.cpp

Utility.o: Source/Utility.cpp include/Book/Utility.hpp \
		include/Book/Utility.inl \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utility.o Source/Utility.cpp

World.o: Source/World.cpp include/Book/World.hpp \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		include/Book/ResourceIdentifiers.hpp \
		include/Book/SceneNode.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		include/Book/SpriteNode.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		include/Book/CommandQueue.hpp \
		include/Book/Command.hpp \
		include/Book/Utility.hpp \
		include/Book/Utility.inl \
		Ball.hpp \
		include/Book/Entity.hpp \
		/usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/Window/Touch.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		Paddle.hpp \
		Level.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o World.o Source/World.cpp

GameState.o: States/Source/GameState.cpp States/Include/GameState.hpp \
		include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		include/Book/World.hpp \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		include/Book/SceneNode.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		include/Book/SpriteNode.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		include/Book/CommandQueue.hpp \
		include/Book/Command.hpp \
		include/Book/Utility.hpp \
		include/Book/Utility.inl \
		Ball.hpp \
		include/Book/Entity.hpp \
		/usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/Touch.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		Paddle.hpp \
		Level.hpp \
		include/Book/Player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameState.o States/Source/GameState.cpp

Ball.o: Ball.cpp Ball.hpp \
		include/Book/Entity.hpp \
		include/Book/SceneNode.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/Window/Touch.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		include/Book/Utility.hpp \
		include/Book/Utility.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ball.o Ball.cpp

Paddle.o: Paddle.cpp Paddle.hpp \
		include/Book/Entity.hpp \
		include/Book/SceneNode.hpp \
		include/Book/Category.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/Window/Touch.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		include/Book/Utility.hpp \
		include/Book/Utility.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Paddle.o Paddle.cpp

MenuState.o: States/Source/MenuState.cpp States/Include/MenuState.hpp \
		include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		include/Book/Utility.hpp \
		include/Book/Utility.inl \
		include/Book/Foreach.hpp \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/System/Clock.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MenuState.o States/Source/MenuState.cpp

PauseState.o: States/Source/PauseState.cpp States/Include/PauseState.hpp \
		include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		include/Book/Utility.hpp \
		include/Book/Utility.inl \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/System/Clock.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PauseState.o States/Source/PauseState.cpp

NewLevel.o: States/Source/NewLevel.cpp States/Include/NewLevel.hpp \
		include/Book/State.hpp \
		include/Book/StateIdentifiers.hpp \
		include/Book/ResourceIdentifiers.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		include/Book/Utility.hpp \
		include/Book/Utility.inl \
		include/Book/ResourceHolder.hpp \
		Include/Book/ResourceHolder.inl \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/System/Clock.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewLevel.o States/Source/NewLevel.cpp

Level.o: Level.cpp Level.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Level.o Level.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Pong/bin || mkdir -p $(INSTALL_ROOT)/opt/Pong/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/Pong/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/Pong/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Pong/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

